added community api calls
mhbo/mhbo-js pull request #24
Opened 2019-08-25 10:57 UTC by vasdhara

#23 
Added query params for the react client to differentiate between a community api call and mobile home api call
added boolean in results to help differentiate
added type definitions for community results
added api call to different endpoint for communities

2019-08-27 10:24 UTC, vasdhara commented
@jimjeffers restructured files as discussed.

2019-08-27 16:55 UTC, jeremy-loss requested changes

2019-08-27 16:55 UTC, jeremy-loss commented on src/types.ts
> +export interface ICommunity {
We have some common fields that I would like to consolidate. To do this I think we should do the following:

interface IMHBOListing {
   id: number,
   address: IAddress,
   isCommunity: boolean,
   url
}

interface ICommunity  extends IMHBOListing {
... remove fields already coming from IMHBOListing
}

interface IMobileHome  extends IMHBOListing {
... remove fields already coming from IMHBOListing
}

For now we can keep photoLarge and photoSmall in the child interfaces. We can always rearrange this later. For performance reasons I would like to prepare for the initial radius search to only return IMHBOListing data and the details be returned and cached based on what needs to be displayed to the user at that time.

2019-08-27 16:55 UTC, jeremy-loss commented on src/types.ts
> +  county: string
Country and county are already part of address so I don't think they are needed.

2019-08-29 05:04 UTC, jeremy-loss approved these changes
This looks good. I will try and get it pushed to npm shortly.

2019-08-29 05:04 UTC, merged